title = "Giochi In Circolo"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "it"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
site_logo = "images/logo.jpg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "red"
  site_logo = "images/logo.jpg"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = ""
